version: "3.7"

services:
  suricata:
    image: ciscoaitle2019/suricata
    network_mode: "host"
    container_name: suricata
    restart: unless-stopped
    environment:
      INTERFACE: "eno2"    ### <--- Modify your monitoring interface here!
    volumes:
      - /var/log/suricata:/var/log/suricata
